services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - rabbit
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
  consumer:
    build: consumer/.
    networks:
      - rabbit
    deploy:
      mode: replicated
      replicas: 3
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true
  producer:
    build: producer/.
    networks:
      - rabbit
    deploy:
      mode: replicated
      replicas: 2
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true

networks:
  rabbit:
    driver: overlay
    attachable: true

